/**
 * @flow
 */
'use strict';

export const allergyCodes = [
{"code":"Acetaminophene"},
{"code":"Advil"},
{"code":"Alcohol"},
{"code":"Almond"},
{"code":"Alphagan"},
{"code":"Amoxicilline"},
{"code":"Amoxil"},
{"code":"Amyxyne"},
{"code":"Anaprox"},
{"code":"Anesthetic"},
{"code":"Animal"},
{"code":"Anti-inflammatory"},
{"code":"Antibiotic"},
{"code":"Apple"},
{"code":"Aquinil"},
{"code":"Aspirine"},
{"code":"Atorvastatin"},
{"code":"Aubergine"},
{"code":"Augmentin"},
{"code":"Avelox"},
{"code":"Avenox"},
{"code":"Azithromycine"},
{"code":"Bactrin"},
{"code":"Bee"},
{"code":"Benadryl"},
{"code":"Bezafibre"},
{"code":"Bezalip"},
{"code":"Biaxin"},
{"code":"Birch"},
{"code":"Caffeine"},
{"code":"Capsaicine"},
{"code":"Cari"},
{"code":"Cats"},
{"code":"Cecla"},
{"code":"Cefaclor"},
{"code":"Cefzil"},
{"code":"Celebrex"},
{"code":"Cephalosporin"},
{"code":"Cephazil"},
{"code":"Chery"},
{"code":"Chlorine"},
{"code":"Clarithromycine"},
{"code":"Clavulin"},
{"code":"Clindamycine"},
{"code":"Codeine"},
{"code":"Cortisone"},
{"code":"Demerol"},
{"code":"Dextrometorphan"},
{"code":"Diachylon"},
{"code":"Dibucaine"},
{"code":"Dilaudid"},
{"code":"Dog"},
{"code":"Dust"},
{"code":"Eggs"},
{"code":"Empracet"},
{"code":"Epinephrine"},
{"code":"Erythromycine"},
{"code":"Estrogel"},
{"code":"Fenofibrate"},
{"code":"Fentanyl"},
{"code":"Fish"},
{"code":"Flour"},
{"code":"Fluviral"},
{"code":"Food coloring"},
{"code":"Fruits"},
{"code":"Fucitalmic"},
{"code":"Fur"},
{"code":"Gluten"},
{"code":"Grapefruit"},
{"code":"Grass"},
{"code":"Horse"},
{"code":"Hydromax"},
{"code":"Hydromorphone"},
{"code":"Ibuprofene"},
{"code":"Imitrex"},
{"code":"Insect bite"},
{"code":"Iode"},
{"code":"Keflex"},
{"code":"Kiwi"},
{"code":"Lactose"},
{"code":"Latex"},
{"code":"Lavander"},
{"code":"Lecithinine"},
{"code":"Lentils"},
{"code":"Lidocaine"},
{"code":"Lincomycine"},
{"code":"Lobster"},
{"code":"Lopressor"},
{"code":"Lorazepam"},
{"code":"Macrolides"},
{"code":"Mais"},
{"code":"Mandarin"},
{"code":"Mango"},
{"code":"Maxidex"},
{"code":"Maxiran"},
{"code":"Melon"},
{"code":"Meperidine"},
{"code":"Mercure"},
{"code":"Metal"},
{"code":"Milk"},
{"code":"Moissisures"},
{"code":"Morphine"},
{"code":"Motrin"},
{"code":"Mustard"},
{"code":"Naproxen"},
{"code":"Nexium"},
{"code":"Nickel"},
{"code":"Novamoxan"},
{"code":"Nuts"},
{"code":"Paint"},
{"code":"Pantoloc"},
{"code":"Peaches"},
{"code":"Peanuts"},
{"code":"Peas"},
{"code":"Penecilline"},
{"code":"Perfume"},
{"code":"Pineaple"},
{"code":"Pisanlit"},
{"code":"Pollen"},
{"code":"Polysporin"},
{"code":"Pravachol"},
{"code":"Quinoa"},
{"code":"Rabit"},
{"code":"Ragweed"},
{"code":"Rosasol"},
{"code":"Seafood"},
{"code":"Septra"},
{"code":"Serax"},
{"code":"Sesame"},
{"code":"Sheep hair"},
{"code":"Shellfish"},
{"code":"Shrimp"},
{"code":"Soap"},
{"code":"Soya"},
{"code":"Strawberries"},
{"code":"Sulfa"},
{"code":"Sun"},
{"code":"Sunscreen"},
{"code":"Tegretol"},
{"code":"Tetanos"},
{"code":"Tetracycline"},
{"code":"Timolol"},
{"code":"Tobradex"},
{"code":"Tobramycine"},
{"code":"Tobrex"},
{"code":"Trees"},
{"code":"Tylenol"},
{"code":"Urticaire"},
{"code":"Valium"},
{"code":"Valtrex"},
{"code":"Vinaigre"},
{"code":"Wasp"},
{"code":"Xylocaine"},
{"code":"Zilocaine"},
{"code":"Zinc PNC"},
{"code":"Zitromax"},
{"code":"Zytromax"}
]

export const allergyReactionCodes = [
{"code":"Abdominal Cramps"},
{"code":"Abdominal Pain"},
{"code":"Anaphylaxis"},
{"code":"Anxiety"},
{"code":"Chest Discomfort"},
{"code":"Chest Tightness"},
{"code":"Diarhea"},
{"code":"Difficulty Breathing"},
{"code":"Difficulty Swallowing"},
{"code":"Dizziness"},
{"code":"Eye Swelling"},
{"code":"Facial Swelling"},
{"code":"Fear"},
{"code":"Feeling of Apprehension"},
{"code":"Headache"},
{"code":"Hives"},
{"code":"Itching"},
{"code":"Light-Headedness"},
{"code":"Nasal Congestion"},
{"code":"Nausea"},
{"code":"Palpitations"},
{"code":"Photosensitivity"},
{"code":"Stomach Cramps"},
{"code":"Tongue Swelling"},
{"code":"Unconsciousness"},
{"code":"Vomiting"},
{"code":"Watery Eye"},
{"code":"Weakness"},
{"code":"Wheezing"}
]
