/*
 * File: app/controller/FavoriteButtonController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.controller.FavoriteButtonController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            parentView: {
                selector: 'ParentView',
                xtype: 'ParentView'
            },
            invoicePanel: {
                selector: 'InvoicePanel',
                xtype: 'InvoicePanel'
            }
        },

        control: {
            "button#mybutton58": {
                tap: 'onFavoriteTap'
            }
        }
    },

    onFavoriteTap: function(button, e, eOpts) {
        var favProducts = new WINK.view.QuickProductSelectionPanel({invoicePanel:this.getInvoicePanel(),parentView:this.getParentView()});


        this.getParentView().setActiveItem(favProducts);

    }

});