/*
 * File: app/controller/LockScreenController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.controller.LockScreenController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            loginPanel: {
                selector: 'LoginPanel',
                xtype: 'LoginPanel'
            },
            parentView: {
                selector: 'ParentView',
                xtype: 'ParentView'
            }
        },

        control: {
            "button#mybutton7": {
                tap: 'onMybutton7Tap'
            }
        }
    },

    onMybutton7Tap: function(button, e, eOpts) {
         this.getParentView().setActiveItem(this.getLoginPanel());
    }

});