/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.controller.LoginController', {
    extend: 'Ext.app.Controller',
    requires: [
        'WINK.Utilities'
    ],
    config: {
        refs: {
            loginPanel: {
                selector: 'LoginPanel',
                xtype: 'LoginPanel'
            },
            parentView: {
                selector: 'ParentView',
                xtype: 'ParentView'
            },
            mainAppPanel: {
                selector: 'MainAppPanel',
                xtype: 'MainAppPanel'
            }
        },
        control: {
            'button#logInButton': {
                tap: 'onMybuttonTap'
            },
            'button[action=goToMainScreen]': {
                tap: 'doGoToMainScreen'
            }

        }
    },
    doGoToMainScreen: function() {
        this.getParentView().setActiveItem(this.getMainAppPanel());
    },
    onMybuttonTap: function() {

        var loginPanel = this.getLoginPanel();
        var myController = this;
        WINK.Utilities.showWorking();
        Ext.Ajax.request({
            url: WINK.Utilities.getRestURL() + 'users/me',
            method: 'GET',
            headers: {
                'wink-username': loginPanel.getUsername(),
                'wink-password': loginPanel.getPassword(),
                'wink-store': loginPanel.getStore(),
                'wink-accountid': WINK.Utilities.getAccountId()
            },
            success: function(response) {

                myController.getParentView().setActiveItem(myController.getMainAppPanel());
                loginPanel.clearForm();
                WINK.Utilities.hideWorking();
            },
            failure: function(response) {
                WINK.Utilities.hideWorking();
                Ext.Msg.alert('Login Failed','Invalid Login...Please try again',Ext.emptyFn);
            },
            callback: function(options, success, response) {


            }
        });
    }

});