/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.controller.LoginController', {
    extend: 'Ext.app.Controller',
     requires: [
        'WINK.Utilities'
    ],
    config: {
        refs: {
            loginPanel: {
                selector: 'LoginPanel',
                xtype: 'LoginPanel'
            },
            parentView: {
                selector: 'ParentView',
                xtype: 'ParentView'
            },
            mainAppPanel: {
                selector: 'MainAppPanel',
                xtype: 'MainAppPanel'
            }
        },
        routes: {
            'mainmenu': 'openMainmenu',
            'login': 'openLogin'
        },
        control: {
            'button#logInButton': {
                tap: 'login'
            },
            'button[action=goToMainScreen]': {
                tap: 'doGoToMainScreen'
            }

        }
    },
    doGoToMainScreen: function() {
        document.location.href = '#mainmenu';
    },
    openMainmenu: function() {
        WINK.Utilities.previousActiveItem = null;
        this.getParentView().setActiveItem(this.getMainAppPanel());
    },
  
    login: function() {

        var loginPanel = this.getLoginPanel();
        var myController = this;

        WINK.Utilities.showWorking();
        Ext.Ajax.request({
            scope:this,
            url: WINK.Utilities.getRestURL() + 'users/me',
            method: 'GET',
            headers: {
                'wink-username': loginPanel.getUsername(),
                'wink-password': loginPanel.getPassword(),
                'wink-store': loginPanel.getStoreId(),
                'wink-accountid': WINK.Utilities.getAccountId()
            },
            success: function(response) {

                WINK.Utilities.currentstore=loginPanel.getStore();
                loginPanel.clearForm();
                if (WINK.Utilities.previousActiveItem)
                {
                    myController.getParentView().setActiveItem(WINK.Utilities.previousActiveItem);
                    WINK.Utilities.previousActiveItem = null;
                } else {
                    myController.getParentView().setActiveItem(myController.getMainAppPanel());
                }
                WINK.Utilities.hideWorking();
                 WINK.Utilities.loadAllRequiredStores();
            },
            failure: function(response) {
                WINK.Utilities.hideWorking();
                Ext.Msg.alert('Login Failed', 'Invalid Login...Please try again', Ext.emptyFn);
            },
            callback: function(options, success, response) {


            }
        });
    }

});