/*
 * File: app/controller/QuicksaleMenuController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.controller.MenuController', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            parentView: {
                selector: 'ParentView',
                xtype: 'ParentView'
            }
        },
        control: {
            'button[action=doNewPatient]': {
                tap: 'onNewPatientButtonTap'
            },
            'button[action=doQuickSale]': {
                tap: 'onQuicksaleButtonTap'
            },
            'button[action=doFindPatient]': {
                tap: 'onFindPatientButtonTap'
            },
            'button[action=doOpenPatient]': {
                tap: 'onOpenPatientTap'
            }
        }
    },
    onOpenPatientTap: function(button, e, eOpts) {
        var patientHistory = Ext.create('WINK.view.PatientHistoryPanel');

        this.getParentView().setActiveItem(patientHistory);
    },
    onQuicksaleButtonTap: function(button, e, eOpts) {
        var quicksale = Ext.create('WINK.view.InvoicePanel');

        this.getParentView().setActiveItem(quicksale);
    },
    onNewPatientButtonTap: function(button, e, eOpts) {
        var newPatientPanel = Ext.create('WINK.view.PatientPanel');

        this.getParentView().setActiveItem(newPatientPanel);
    },
    onFindPatientButtonTap: function(button, e, eOpts) {
        if (!this.findPatientPanel)
            this.findPatientPanel = Ext.create('WINK.view.FindPatientPanel');

        this.getParentView().setActiveItem(this.findPatientPanel);
    },
    onDeliveryJobButtonTap: function(button, e, eOpts) {
        var newPatientPanel = Ext.create('WINK.view.PatientPanel');

        this.getParentView().setActiveItem(newPatientPanel);
    },
    onNewInvoiceButtonTap: function(button, e, eOpts) {
        var newPatientPanel = Ext.create('WINK.view.PatientPanel');

        this.getParentView().setActiveItem(newPatientPanel);
    }

});