/*
 * File: app/controller/QuicksaleMenuController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.controller.MenuController', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            parentView: {
                selector: 'ParentView',
                xtype: 'ParentView'
            }
        },
        routes: {
            'patient/:patientid': 'openPatient',
            'findpatient': 'openFindPatient',
            'newpatient': 'openNewPatient',
            'newquicksale':'openQuicksale'
        },
        control: {
            'button[action=doNewPatient]': {
                tap: 'onNewPatientButtonTap'
            },
            'button[action=doQuickSale]': {
                tap: 'onQuicksaleButtonTap'
            },
            'button[action=doFindPatient]': {
                tap: 'onFindPatientButtonTap'
            },
            'button[action=doOpenPatient]': {
                tap: 'onOpenPatientTap'
            },
            'button[action=goBack]': {
                tap: 'goBack'
            },
        }
    },
    goBack:function(){
        history.back();
    },  
    openPatient: function(patientid) {
        WINK.Utilities.showWorking();
        WINK.model.Patient.load(patientid, {
            scope: this,
            failure: function(patient, operation) {
                WINK.Utilities.hideWorking();
                WINK.Utilities.showAjaxError('Open Patient', operation);
            },
            success: function(patient, operation) {
                console.log('Loaded Patient' + patient.getId() + " " + patient.get('lastname'));
                var patientHistory = Ext.create('WINK.view.PatientHistoryPanel');

                this.getParentView().setActiveItem(patientHistory);
                WINK.Utilities.hideWorking();

                patientHistory.loadPatient(patient);


            },
            callback: function(patient, operation) {

            }
        });


        /*
         var history = new WINK.model.Patienthistory({
         id: patientid
         });
         alert(history.get('id'));
         var invoices =  history.invoices();
         invoices.load();
         history.getPatient({
         reload: true,
         callback: function(patient, operation) {
         WINK.Utilities.hideWorking();
         console.info("getpatient callback");
         alert(patient.get('firstname'));
         },
         success: function(patient, operation) {
         WINK.Utilities.hideWorking();
         console.info("getpatient success");
         },
         failure: function(patient, operation) {
         WINK.Utilities.hideWorking();
         console.info("getpatient failure");
         }, 
         scope: this});
         */
        /*
         WINK.model.Patient.load(id, {
         scope: this,
         failure: function(record, operation) {
         WINK.Utilities.showAjaxError('Open Patient');
         },
         success: function(record, operation) {
         var patientHistory = Ext.create('WINK.view.PatientHistoryPanel');
         
         this.getParentView().setActiveItem(patientHistory);
         },
         callback: function(record, operation) {
         WINK.Utilities.hideWorking();
         }
         });
         */


    },
    onOpenPatientTap: function(button, e, eOpts) {
        var patientHistory = Ext.create('WINK.view.PatientHistoryPanel');

        this.getParentView().setActiveItem(patientHistory);
    },
    onQuicksaleButtonTap: function(button, e, eOpts) {
        document.location.href = '#newquicksale';
    },
    openQuicksale: function(button, e, eOpts) {
        var quicksale = Ext.create('WINK.view.InvoicePanel');

        this.getParentView().setActiveItem(quicksale);
    },
    onNewPatientButtonTap: function(button, e, eOpts) {
        document.location.href = '#newpatient';
    },
    openNewPatient: function(button, e, eOpts) {
        var newPatientPanel = Ext.create('WINK.view.PatientPanel');

        this.getParentView().setActiveItem(newPatientPanel);
    },
    openFindPatient: function() {
        if (!this.findPatientPanel)
            this.findPatientPanel = Ext.create('WINK.view.FindPatientPanel');

        this.getParentView().setActiveItem(this.findPatientPanel);
    },
    onFindPatientButtonTap: function(button, e, eOpts) {
        document.location.href = "#findpatient";

    },
    onDeliveryJobButtonTap: function(button, e, eOpts) {

    },
    onNewInvoiceButtonTap: function(button, e, eOpts) {

    }

});