/*
 * File: app/controller/QuicksaleMenuController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.controller.MenuController', {
    extend: 'Ext.app.Controller',
    requires: [
        'WINK.Utilities'
    ],
    config: {
        refs: {
            parentView: {
                selector: 'ParentView',
                xtype: 'ParentView'
            }
        },
        before: {
            openPatient: 'beforeRoute',
            openInvoice: 'beforeRoute',
            openWorksheet:'beforeRoute',
            openRxOrder:'beforeRoute',
            openFindPatient: 'beforeRoute',
            openNewPatient: 'beforeRoute',
            openQuicksale: 'beforeRoute'
        },
        routes: {
            'patient/:patientid': 'openPatient',
            //  'patientinvoice/:patientid/:invoiceid': 'openPatientInvoice',
            'invoice/:invoiceid': 'openInvoice',
            'findpatient': 'openFindPatient',
            'newpatient': 'openNewPatient',
            'newquicksale': 'openQuicksale',
            'i:invoiceid': 'openInvoice',
            'r:invoiceid': 'openWorksheet',
            'o:invoiceid': 'openRxOrder',
            'z:patientid': 'openPatient'
        },
        control: {
            'button[action=doNewPatient]': {
                tap: 'onNewPatientButtonTap'
            },
            'button[action=doQuickSale]': {
                tap: 'onQuicksaleButtonTap'
            },
            'button[action=doFindPatient]': {
                tap: 'onFindPatientButtonTap'
            },
            'button[action=doOpenPatient]': {
                tap: 'onOpenPatientTap'
            },
            'button[action=goBack]': {
                tap: 'goBack'
            },
        }
    },
    goBack: function() {
        history.back();
    },
    beforeRoute: function(action) {
        console.log('MenuController.beforeRoute()');
        WINK.Utilities.showWorking();
        WINK.Utilities.loadAllRequiredStores(function() {
            console.log('MenuController.beforeRoute() callback');
            WINK.Utilities.hideWorking();
            action.resume();

        });
    },
    openWorksheet: function(worksheetid){
       var me = this;

        WINK.model.RxWorksheet.load(worksheetid, {
            success: function(worksheet) {
                console.log('loaded worksheet ' + worksheet.get('id')); 
                console.log('for patient invoice ' + worksheet.get('patientinvoice_idpatientinvoice')); 

                me.openInvoice(worksheet.get('patientinvoice_idpatientinvoice'));
            }
        });
    },
    openRxOrder: function(orderid){
         var me = this;

        WINK.model.RxOrderForm.load(orderid, {
            success: function(rxorder) {
                console.log('loaded rx order ' + rxorder.get('id')); 
                console.log('for worksheet ' + rxorder.get('rxworksheet_idrxworksheet')); 
                me.openWorksheet(rxorder.get('rxworksheet_idrxworksheet'));
            }
        });
    },
    openInvoice: function(invoiceid) {

        var me = this;

        WINK.model.PatientInvoice.load(invoiceid, {
            success: function(invoice) {
                console.log('loaded invoice ' + invoice.get('id')); 

                if (invoice.get('patient_idpatient') && invoice.get('patient_idpatient') > 0)
                {
                    me.openPatientInvoice(invoice.get('patient_idpatient'), invoiceid);
                } else {
                    var quicksale = Ext.create('WINK.view.InvoicePanel');

                    me.getParentView().setActiveItem(quicksale);
                    quicksale.loadPatientInvoice(invoice);
                }

            }
        });


    },
    openPatientInvoice: function(patientid, invoiceid) {
        this.openPatient(patientid);
    },
    openPatient: function(patientid) {

        WINK.model.Patient.load(patientid, {
            scope: this,
            failure: function(patient, operation) {
                WINK.Utilities.hideWorking();
                WINK.Utilities.showAjaxError('Open Patient', operation);
            },
            success: function(patient, operation) {
                console.log('Loaded Patient' + patient.getId() + " " + patient.get('lastname'));
                var patientHistory = Ext.create('WINK.view.PatientHistoryPanel');

                this.getParentView().setActiveItem(patientHistory);
                WINK.Utilities.hideWorking();

                patientHistory.loadPatient(patient);


            },
            callback: function(patient, operation) {

            }
        });


        /*
         var history = new WINK.model.Patienthistory({
         id: patientid
         });
         alert(history.get('id'));
         var invoices =  history.invoices();
         invoices.load();
         history.getPatient({
         reload: true,
         callback: function(patient, operation) {
         WINK.Utilities.hideWorking();
         console.info("getpatient callback");
         alert(patient.get('firstname'));
         },
         success: function(patient, operation) {
         WINK.Utilities.hideWorking();
         console.info("getpatient success");
         },
         failure: function(patient, operation) {
         WINK.Utilities.hideWorking();
         console.info("getpatient failure");
         }, 
         scope: this});
         */
        /*
         WINK.model.Patient.load(id, {
         scope: this,
         failure: function(record, operation) {
         WINK.Utilities.showAjaxError('Open Patient');
         },
         success: function(record, operation) {
         var patientHistory = Ext.create('WINK.view.PatientHistoryPanel');
         
         this.getParentView().setActiveItem(patientHistory);
         },
         callback: function(record, operation) {
         WINK.Utilities.hideWorking();
         }
         });
         */


    },
    onOpenPatientTap: function(button, e, eOpts) {
        var patientHistory = Ext.create('WINK.view.PatientHistoryPanel');

        this.getParentView().setActiveItem(patientHistory);
    },
    onQuicksaleButtonTap: function(button, e, eOpts) {
        document.location.href = '#newquicksale';
    },
    openQuicksale: function() {
        console.log('MenuController.openQuicksale()');
        var model = Ext.create('WINK.model.PatientInvoice');
        WINK.Utilities.setDefaultValues(model);

        var quicksale = Ext.create('WINK.view.InvoicePanel');

        

        this.getParentView().setActiveItem(quicksale);
        quicksale.loadPatientInvoice(model);
    },
    onNewPatientButtonTap: function(button, e, eOpts) {
        document.location.href = '#newpatient';
    },
    openNewPatient: function() {
        var newPatientPanel = Ext.create('WINK.view.PatientPanel');

        this.getParentView().setActiveItem(newPatientPanel);
    },
    openFindPatient: function() {
        if (!this.findPatientPanel)
            this.findPatientPanel = Ext.create('WINK.view.FindPatientPanel');

        this.getParentView().setActiveItem(this.findPatientPanel);
    },
    onFindPatientButtonTap: function(button, e, eOpts) {
        document.location.href = "#findpatient";

    },
    onDeliveryJobButtonTap: function(button, e, eOpts) {

    },
    onNewInvoiceButtonTap: function(button, e, eOpts) {

    }

});