/*
 * File: app/view/InputPrescriptionPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.view.InputPrescriptionPanel', {
    extend: 'Ext.Container',

    requires: [
        'Ext.Container',
        'Ext.Button'
    ],

    config: {
        layout: 'hbox',
        items: [
            {
                xtype: 'container',
                margin: '0 10 0 10',
                width: 62,
                items: [
                    {
                        xtype: 'button',
                        height: 50,
                        margin: '5 5 5 5',
                        width: 50,
                        text: '+'
                    },
                    {
                        xtype: 'button',
                        height: 50,
                        margin: '5 5 5 5',
                        width: 50,
                        text: '-'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 219,
                margin: '0 10 0 10',
                width: 59,
                items: [
                    {
                        xtype: 'button',
                        height: 50,
                        margin: '5 5 5 5',
                        width: 50,
                        text: '1'
                    },
                    {
                        xtype: 'button',
                        height: 50,
                        margin: '5 5 5 5',
                        width: 50,
                        text: '2'
                    },
                    {
                        xtype: 'button',
                        height: 50,
                        margin: '5 5 5 5',
                        width: 50,
                        text: '3'
                    },
                    {
                        xtype: 'button',
                        height: 50,
                        margin: '5 5 5 5',
                        width: 50,
                        text: '.75'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 219,
                margin: '0 10 0 10',
                width: 59,
                items: [
                    {
                        xtype: 'button',
                        height: 50,
                        margin: '5 5 5 5',
                        width: 50,
                        text: '.00'
                    },
                    {
                        xtype: 'button',
                        height: 50,
                        margin: '5 5 5 5',
                        width: 50,
                        text: '.25'
                    },
                    {
                        xtype: 'button',
                        height: 50,
                        margin: '5 5 5 5',
                        width: 50,
                        text: '.50'
                    },
                    {
                        xtype: 'button',
                        height: 50,
                        margin: '5 5 5 5',
                        width: 50,
                        text: '.75'
                    }
                ]
            }
        ]
    }

});