/*
 * File: app/view/InvoicePanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.view.InvoicePanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.InvoicePanel',

    requires: [
        'WINK.view.InvoiceItemPanel',
        'WINK.view.InvoiceSummary',
        'Ext.tab.Panel',
        'Ext.field.Text',
        'Ext.Button',
        'Ext.SegmentedButton',
        'Ext.Label',
        'Ext.tab.Bar',
        'Ext.form.Panel'
    ],

    config: {
        layout: 'hbox',
          centered: false,
       // modal: false,
        scrollable: false,
        
        items: [
            
            {
                xtype: 'tabpanel',
                flex: 1,
                id: 'invoiceTabPanel',
                itemId: 'invoiceTabPanel',
                items: [
                    {
                        xtype: 'container',
                        title: 'Invoice',
                        iconCls: 'info',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'container',
                                border: '0 0 1 0',
                                height: 50,
                                style: 'background:rgb(215,224,231); border-style:solid; border-color: darkgrey;'
                            },
                            {
                                xtype: 'container',
                                border: '1 0 0 0',
                                height: 65,
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        flex: 0,
                                        border: '0 1 0 0',
                                        padding: '0 30 0 10',
                                        style: 'background:rgb(222,238,252); border-style:solid; border-color: darkgrey;',
                                        layout: {
                                            type: 'hbox',
                                            align: 'center',
                                            pack: 'center'
                                        },
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                cls: 'inputBorder',
                                                height: 40,
                                                margin: '2 0 2 2',
                                                width: 200,
                                                label: '',
                                                placeHolder: 'Item'
                                            },
                                            {
                                                xtype: 'button',
                                                cls: 'buttonSquare',
                                                height: 45,
                                                margin: '2 2 2 0',
                                                ui: 'action',
                                                text: 'Search'
                                            },
                                            {
                                                xtype: 'button',
                                                cls: 'buttonSquare',
                                                height: 45,
                                                itemId: 'mybutton58',
                                                margin: '0 0 0 5',
                                                ui: 'confirm',
                                                text: 'Favorites'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        border: 0,
                                        padding: '0 0 0 10',
                                        style: 'background:#DDE9D2; border-style:solid; border-color: darkgrey;',
                                        layout: {
                                            type: 'hbox',
                                            align: 'center'
                                        },
                                        items: [
                                            {
                                                xtype: 'segmentedbutton',
                                                margin: '0 0 0 5',
                                                allowToggle: false,
                                                items: [
                                                    {
                                                        xtype: 'button',
                                                        itemId: 'mybutton17',
                                                        text: '+ Rx'
                                                    },
                                                    {
                                                        xtype: 'button',
                                                        text: '+ CL'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'segmentedbutton',
                                                margin: '5 5 5 5',
                                                allowToggle: false,
                                                items: [
                                                    {
                                                        xtype: 'button',
                                                        text: 'Camera'
                                                    },
                                                    {
                                                        xtype: 'button',
                                                        text: 'Attachment'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                border: '1 0 1 0',
                                style: 'background:rgb(248,248,248); border-style:solid; border-color: darkgrey;',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'label',
                                        flex: 1,
                                        html: 'Product Name',
                                        margin: '5 2 5 5'
                                    },
                                    {
                                        xtype: 'label',
                                        html: 'Qty',
                                        margin: '5 2 0 0',
                                        width: 100
                                    },
                                    {
                                        xtype: 'label',
                                        html: 'Unit Price',
                                        margin: '5 2 0 0',
                                        width: 100
                                    },
                                    {
                                        xtype: 'label',
                                        html: 'Tax',
                                        margin: '5 2 0 0',
                                        width: 100
                                    },
                                    {
                                        xtype: 'label',
                                        html: 'Total',
                                        margin: '5 2 0 0',
                                        width: 100
                                    },
                                    {
                                        xtype: 'label',
                                        html: '',
                                        margin: '5 2 0 0',
                                        width: 50
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                style: 'background-color: #ffffff; border-style:solid!important; border:1px; border-color: darkgrey;',
                                layout: 'vbox',
                                scrollable: 'vertical',
                                items: [
                                    {
                                        xtype: 'mycontainer10',
                                        margin: 5
                                    },
                                    {
                                        xtype: 'mycontainer10',
                                        invoiceItemIndex: 1,
                                        margin: 5
                                    },
                                    {
                                        xtype: 'mycontainer10',
                                        invoiceItemIndex: 2,
                                        margin: 5
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Job Status',
                        iconCls: 'info'
                    },
                    {
                        xtype: 'container',
                        title: 'New CL',
                        iconCls: 'info'
                    }
                ],
                tabBar: {
                    docked: 'bottom',
                    ui: 'light'
                }
            },
            {
                xtype: 'InvoiceSummary'
            }
        ],
        listeners: [
            {
                fn: 'onMybutton17Tap',
                event: 'tap',
                delegate: '#mybutton17'
            }
        ]
    },

    onMybutton17Tap: function(button, e, eOpts) {
        var newSheet = new WINK.view.RxWorksheetPanel({title:"New Rx"});
        var tabPanel = Ext.getCmp("invoiceTabPanel");
        tabPanel.add(newSheet);
    }

});