/*
 * File: app/view/InvoiceSummary.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.view.InvoiceSummary', {
    extend: 'Ext.form.Panel',
    alias: 'widget.InvoiceSummary',
    requires: [
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.Label',
        'Ext.SegmentedButton'
    ],
    loadPatientInvoice: function(model) {
        this.setRecord(model);
    },
    config: {
        border: 1,
        style: 'background-color: #eee; border-color: darkgrey; border-style: solid;',
        width: 220,
        layout: 'fit',
        items: [
            {
                xtype: 'container',
                margin: 20,
                layout: 'vbox',
                items: [
                    {
                        xtype: 'selectfield',
                        store: 'LocationStore',
                        margin: '5 0 5 0',
                        label: '',
                        labelWidth: '0%',
                        disabled: true,
                        value: 'id',
                        displayField: 'name',
                        name: 'store_idstore',
                        title:'Store'
                    },
                    {
                        xtype: 'datepickerfield',
                        margin: '5 0 5 0',
                        label: 'O',
                        labelWidth: '20%',
                        disabled: true,
                        name: 'orderdate',
                       
                    },
                    {
                        xtype: 'datepickerfield',
                        margin: '5 0 5 0',
                        label: 'P',
                        labelWidth: '20%',
                        placeHolder: 'Not Promissed',
                        name: 'promisseddate',
                        
                    },
                    {
                        xtype: 'datepickerfield',
                        margin: '5 0 5 0',
                        label: 'D',
                        labelWidth: '20%',
                        placeHolder: 'Open',
                        name: 'delivereddate'
                        

                    },
                    {
                        xtype: 'container',
                        border: '0 0 1 0',
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Subtotal',
                                style: 'color: darkgrey'
                            },
                            {
                                xtype: 'label',
                                html: '$0.00',
                                style: 'color: darkgrey'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        border: '0 0 1 0',
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Tax 1',
                                style: 'color: darkgrey'
                            },
                            {
                                xtype: 'label',
                                html: '$0.00',
                                style: 'color: darkgrey'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        border: '0 0 1 0',
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Tax 2',
                                style: 'color: darkgrey'
                            },
                            {
                                xtype: 'label',
                                html: '$0.00',
                                style: 'color: darkgrey'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        border: '0 0 1 0',
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Total',
                                style: 'color: darkgrey'
                            },
                            {
                                xtype: 'label',
                                html: '$0.00',
                                style: 'color: darkgrey'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        border: '0 0 1 0',
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Insurance',
                                style: 'color: darkgrey'
                            },
                            {
                                xtype: 'label',
                                html: '$0.00',
                                style: 'color: darkgrey'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        border: '0 0 1 0',
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Patient',
                                style: 'color: darkgrey'
                            },
                            {
                                xtype: 'label',
                                html: '$0.00',
                                style: 'color: darkgrey'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        border: '0 0 1 0',
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Pay',
                                style: 'color: darkgrey'
                            },
                            {
                                xtype: 'label',
                                html: '$0.00',
                                style: 'color: darkgrey'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        border: 0,
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Balance',
                                style: 'color: black'
                            },
                            {
                                xtype: 'label',
                                html: '$0.00',
                                style: 'color: black'
                            }
                        ]
                    },
                    {
                        xtype: 'segmentedbutton',
                        margin: '20 0 0 0',
                        allowToggle: false,
                        items: [
                            {
                                xtype: 'button',
                                ui: 'confirm',
                                width: 90,
                                text: 'Payment'
                            },
                            {
                                xtype: 'button',
                                width: 90,
                                text: 'Deliver'
                            }
                        ]
                    },
                    {
                        xtype: 'segmentedbutton',
                        margin: '5 0 0 0 ',
                        allowToggle: false,
                        items: [
                            {
                                xtype: 'button',
                                ui: 'action',
                                width: 90,
                                text: 'Print'
                            },
                            {
                                xtype: 'button',
                                ui: 'action',
                                width: 90,
                                text: 'Email'
                            }
                        ]
                    },
                    {
                        xtype: 'segmentedbutton',
                        margin: '20 0 0 0 ',
                        allowToggle: false,
                        items: [
                            {
                                xtype: 'button',
                                ui: 'action',
                                width: 90,
                                text: 'Save'
                            },
                            {
                                xtype: 'button',
                                ui: 'decline',
                                width: 90,
                                text: 'Delete'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container'
            }
        ]
    }

});