/*
 * File: app/view/InvoiceSummary.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.view.InvoiceSummary', {
    extend: 'Ext.form.Panel',
    alias: 'widget.InvoiceSummary',
    requires: [
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.Label',
        'Ext.SegmentedButton'
    ],
    loadPatientInvoice: function(model) {
        this.setRecord(model);
    },
    updateSummary: function() {
        var subtotalLabel = this.down('label[name=subtotal]');
        var tax1Label = this.down('label[name=tax1]');
        var tax2Label = this.down('label[name=tax2]');
        var tax1NameLabel = this.down('label[name=tax1name]');
        var tax2NameLabel = this.down('label[name=tax2name]');
        var totalLabel = this.down('label[name=total]');
        var insuranceLabel = this.down('label[name=insuranceportion]');
        var patientLabel = this.down('label[name=patientportion]');
        var paymentsLabel = this.down('label[name=payments]');
        var patientbalanceLabel = this.down('label[name=balance]');


        var invoicePanel = this.up('InvoicePanel');
        var subtotal = invoicePanel.getSubtotal();
        var tax1 = invoicePanel.getTax1();
        var tax2 = invoicePanel.getTax2();
        var total = subtotal + tax1 + tax2;
        var insurancePortion = invoicePanel.getInsurancePortion();
        var totalPayments = invoicePanel.getPatientPaymentsTotal();
        subtotalLabel.setHtml(subtotal.toFixed(2));
        tax1Label.setHtml(tax1.toFixed(2));
        tax2Label.setHtml(tax2.toFixed(2));
        totalLabel.setHtml(total.toFixed(2));
        insuranceLabel.setHtml(insurancePortion.toFixed(2));
        patientLabel.setHtml((total - insurancePortion).toFixed(2));
        paymentsLabel.setHtml(totalPayments.toFixed(2));
        patientbalanceLabel.setHtml((total - insurancePortion - totalPayments).toFixed(2));

        tax1NameLabel.setHtml(invoicePanel.getTax1Name());
        tax2NameLabel.setHtml(invoicePanel.getTax2Name());

    },
    config: {
        border: 1,
        style: 'background-color: #eee; border-color: darkgrey; border-style: solid;',
        width: 220,
        layout: 'fit',
        items: [
            {
                xtype: 'container',
                margin: 20,
                layout: 'vbox',
                items: [
                    {
                        xtype: 'selectfield',
                        store: 'LocationStore',
                        margin: '5 0 5 0',
                        label: '',
                        labelWidth: '0%',
                        readOnly: true,
                        valueField: 'id',
                        displayField: 'name',
                        name: 'store_idstore',
                        title: 'Store'
                    },
                    {
                        xtype: 'datepickerfield',
                        margin: '5 0 5 0',
                        label: 'O',
                        labelWidth: '20%',
                        readOnly: true,
                        name: 'orderdate'

                    },
                    {
                        xtype: 'datepickerfield',
                        margin: '5 0 5 0',
                        label: 'P',
                        labelWidth: '20%',
                        placeHolder: 'Not Promissed',
                        name: 'promisseddate'

                    },
                    {
                        xtype: 'datepickerfield',
                        margin: '5 0 5 0',
                        label: 'D',
                        labelWidth: '20%',
                        placeHolder: 'Open',
                        name: 'delivereddate'


                    },
                    {
                        xtype: 'container',
                        border: '0 0 1 0',
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Subtotal',
                                style: 'color: darkgrey'
                            },
                            {
                                xtype: 'label',
                                html: '0.00',
                                style: 'color: darkgrey',
                                name: 'subtotal'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        border: '0 0 1 0',
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Tax 1',
                                style: 'color: darkgrey',
                                name: 'tax1name'
                            },
                            {
                                xtype: 'label',
                                html: '0.00',
                                style: 'color: darkgrey',
                                name: 'tax1'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        border: '0 0 1 0',
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Tax 2',
                                style: 'color: darkgrey',
                                name: 'tax2name'
                            },
                            {
                                xtype: 'label',
                                html: '0.00',
                                style: 'color: darkgrey',
                                name: 'tax2'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        border: '0 0 1 0',
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Total',
                                style: 'color: darkgrey'
                            },
                            {
                                xtype: 'label',
                                html: '0.00',
                                style: 'color: darkgrey',
                                name: 'total'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        border: '0 0 1 0',
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Insurance',
                                style: 'color: darkgrey'
                            },
                            {
                                xtype: 'label',
                                html: '0.00',
                                style: 'color: darkgrey',
                                name: 'insuranceportion'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        border: '0 0 1 0',
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Patient',
                                style: 'color: darkgrey'
                            },
                            {
                                xtype: 'label',
                                html: '0.00',
                                style: 'color: darkgrey',
                                name: 'patientportion'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        border: '0 0 1 0',
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Payments',
                                style: 'color: darkgrey'
                            },
                            {
                                xtype: 'label',
                                html: '0.00',
                                style: 'color: darkgrey',
                                name: 'payments'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        border: 0,
                        padding: 5,
                        style: 'border-style: solid; border-color:darkgrey;',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Balance',
                                style: 'color: black'
                            },
                            {
                                xtype: 'label',
                                html: '0.00',
                                style: 'color: black',
                                name: 'balance'
                            }
                        ]
                    },
                    {
                        xtype: 'segmentedbutton',
                        margin: '20 0 0 0',
                        allowToggle: false,
                        items: [
                            {
                                xtype: 'button',
                                ui: 'confirm',
                                width: 90,
                                text: 'Pay',
                                handler: function(btn) {
                                    btn.up('InvoicePanel').pay();
                                }
                            },
                            {
                                xtype: 'button',
                                width: 90,
                                text: 'Deliver',
                                handler: function(btn) {
                                    btn.up('InvoicePanel').deliver();
                                }
                            }
                        ]
                    },
                    {
                        xtype: 'segmentedbutton',
                        margin: '5 0 0 0 ',
                        allowToggle: false,
                        items: [
                            {
                                xtype: 'button',
                                ui: 'action',
                                width: 90,
                                text: 'Print',
                                handler: function(btn) {
                                    btn.up('InvoicePanel').print();
                                }
                            },
                            {
                                xtype: 'button',
                                ui: 'action',
                                width: 90,
                                text: 'Email',
                                handler: function(btn) {
                                    btn.up('InvoicePanel').email();
                                }
                            }
                        ]
                    },
                    {
                        xtype: 'segmentedbutton',
                        margin: '20 0 0 0 ',
                        allowToggle: false,
                        items: [
                            {
                                xtype: 'button',
                                ui: 'action',
                                width: 90,
                                text: 'Save',
                                handler: function(btn) {
                                    btn.up('InvoicePanel').save();
                                }
                            },
                            {
                                xtype: 'button',
                                ui: 'decline',
                                width: 90,
                                text: 'Delete',
                                handler: function(btn) {
                                    btn.up('InvoicePanel').delete();
                                }
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container'
            }
        ]
    }

});