/*
 * File: app/view/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.view.LoginPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.LoginPanel',
    requires: [
        'Ext.TitleBar',
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.field.Email',
        'Ext.field.Password',
        'Ext.Button'
    ],
    getUsername: function() {
        return this.down("emailfield").getValue();
    },
    getPassword: function() {
        return this.down("passwordfield").getValue();
    },
    getStoreId: function() {
        return this.down("selectfield").getValue();
    },
    getStore: function() {
        return this.down("selectfield").getRecord();
    },
    clearForm: function() {
        this.down("emailfield").setValue("");
        this.down("passwordfield").setValue("");
    },
   
    config: {
         
        centered: false,
        fullscreen: false,
        hidden: false,
        id: 'LoginPanel',
        layout: 'fit',
        modal: false,
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'WINK Login'
            },
            {
                xtype: 'container',
                items: [
                    {
                        xtype: 'fieldset',
                        centered: true,
                        height: 212,
                        id: 'LogInFieldSet',
                        width: 550,
                        instructions: '',
                        title: '',
                        items: [
                            {
                                xtype: 'selectfield',
                                label: 'Location',
                                required: true,
                                displayField: 'name',
                                store: 'LocationStore',
                                usePicker: true,
                                valueField: 'id'
                            },
                            {
                                xtype: 'emailfield',
                                label: 'Username',
                                required: true,
                                placeHolder: 'email@example.com'
                            },
                            {
                                xtype: 'passwordfield',
                                label: 'Password',
                                name: 'Password',
                                required: true,
                                placeHolder: 'password',
                                revealable: true
                            },
                            {
                                xtype: 'button',
                                docked: 'bottom',
                                itemId: 'logInButton',
                                ui: 'action',
                                text: 'Log In'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});