/*
 * File: app/view/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.view.LoginPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.LoginPanel',
    requires: [
        'Ext.TitleBar',
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.field.Email',
        'Ext.field.Password',
        'Ext.Button',
        'WINK.store.LocationStore'
    ],
    getUsername: function() {
        return this.down("emailfield").getValue();
    },
    getPassword: function() {
        return this.down("passwordfield").getValue();
    },
    getStoreId: function() {
        return this.down("selectfield").getValue();
    },
    getStore: function() {
        return this.down("selectfield").getRecord();
    },
    clearForm: function() {
        this.down("emailfield").setValue("");
        this.down("passwordfield").setValue("");
    },
    config: {
        centered: false,
        fullscreen: false,
        hidden: false,
        id: 'LoginPanel',
        layout: 'fit',
        modal: false,
        scrollable: false,
        listeners: {
            activate: function(self) {
                self.down('label').setHtml(WINK.Utilities.getDeviceID() + ", Click here to check for updates.");
            }
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'WINK ' + WINK.Utilities.getWinkVersion()
            },
            {
                xtype: 'container',
                docked: 'bottom',
                height: 25,
                style: 'background-color: #eee; border-color: darkgrey; border-style: solid;',
                border: 1,
                layout: 'hbox',
                items: [
                    {
                        xtype: 'label',
                        html: WINK.Utilities.getDeviceID(),
                        margin: 5,
                        style: 'font-size:10px',
                        flex: 0,
                        listeners:
                                {
                                    element: 'element',
                                    tap: function(e, t)
                                    {
                                        WINK.Utilities.launchWebStart();
                                    }
                                }

                    },
                    {
                        xtype: 'label',
                        html: '',
                        margin: 5,
                        style: 'font-size:10px',
                        flex: 1
                    },
                    {
                        xtype: 'label',
                        html: "WINK Technologies Inc. - <a href='tel:+18887644318'>1.888.764.4318</a> - <a href='mailto:support@downloadwink.com'>support@downloadwink.com</a>",
                        margin: 5,
                        style: 'font-size:10px',
                        flex: 0
                    }

                ]
            },
            {
                xtype: 'container',
                items: [
                    {
                        xtype: 'fieldset',
                        centered: true,
                        width: 550,
                        instructions: '',
                        title: '',
                        items: [
                            {
                                xtype: 'selectfield',
                                label: 'Location',
                                required: true,
                                displayField: 'name',
                                store: 'LocationStore',
                                usePicker: true,
                                valueField: 'id'
                            },
                            {
                                xtype: 'emailfield',
                                label: 'Username',
                                required: true,
                                placeHolder: 'email@example.com'
                            },
                            {
                                xtype: 'passwordfield',
                                label: 'Password',
                                name: 'Password',
                                required: true,
                                placeHolder: 'password',
                                revealable: false
                            },
                            {
                                xtype: 'button',
                                docked: 'bottom',
                                margin: '5 0 5 0',
                                itemId: 'logInButton',
                                ui: 'action',
                                text: 'Log In'
                            }




                        ]
                    }
                ]
            }
        ]
    }

});