/*
 * File: app/view/MainAppPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.view.MainAppPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.MainAppPanel',
    requires: [
        'Ext.dataview.NestedList',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer'
    ],
    config: {
        centered: false,
        itemId: 'WinkAppContent',
        items: [
            {
                xtype: 'nestedlist',
                docked: 'left',
                height: '100%',
                hidden: true,
                itemId: 'mynestedlist',
                maxWidth: 500,
                minWidth: 200,
                hideOnMaskTap: false,
                scrollable: false,
                displayField: 'name',
                store: 'leftNavigationTreeStore',
                title: 'Menu',
                layout: {
                    type: 'card',
                    animation: 'slide'
                }
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                itemId: 'winkAppToolbar',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'showHideSideMenuButton',
                        ui: 'action-small',
                        text: '...',
                        hidden:true
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'mybutton7',
                        ui: 'decline-small',
                        text: 'Lock'
                    }
                ]
            },
            {
                xtype: 'container',
                centered: true,
                layout: 'vbox',
                items: [
                    {
                        xtype: 'container',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'container',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'button',
                                        cls: 'mainMenuButton',
                                        height: 125,
                                        width: 125,
                                        text: 'Quicksale',
                                        action: 'doQuickSale'
                                    },
                                    {
                                        xtype: 'button',
                                        cls: 'mainMenuButton',
                                        height: 125,
                                        width: 125,
                                        text: 'New Patient',
                                        itemId: 'NewPatientButton',
                                        hidden: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'button',
                                        cls: 'mainMenuButton',
                                        height: 125,
                                        width: 125,
                                        text: 'Find Patient',
                                        action: 'doFindPatient'
                                    },
                                    {
                                        xtype: 'button',
                                        cls: 'mainMenuButton',
                                        height: 125,
                                        width: 125,
                                        text: 'Deliver Job',
                                        hidden: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'button',
                                        cls: 'mainMenuButton',
                                        height: 125,
                                        width: 125,
                                        text: 'New Patient',
                                        action: 'doNewPatient'
                                    },
                                    {
                                        xtype: 'button',
                                        cls: 'mainMenuButton',
                                        height: 125,
                                        width: 125,
                                        text: 'MyButton4',
                                        hidden: true
                                    }
                                ]
                            }


                        ]
                    },
                    {
                        // instructions: 'Please enter any of the fields above to find your patient',
                        xtype: 'fieldset',
                        title: 'Quick Find',
                        winkname: 'quickfind',
                        defaults: {
                            labelWidth: '35%'
                                    //   labelAlign: 'top'
                        },
                        items: [
                            {
                                xtype: "textfield",
                                name: "winkfile",
                                label: "Wink File ",
                                placeHolder: 'i,r,z,s,o'

                            },
                            {
                                xtype: "textfield",
                                flex: 1,
                                name: "paperfile",
                                label: "Patient Folder"
                            },
                            {
                                xtype: "textfield",
                                name: "tray",
                                label: "Tray"
                            },
                            {
                                xtype: 'button',
                                docked: 'bottom',
                                margin: '5 0 5 0',
                                ui: 'action',
                                text: 'Open',
                                handler: function(button, event) {
                                    console.log("Quickfind.handler()");
                                    var quick = button.up('fieldset[winkname=quickfind]').down('textfield[name=winkfile]').getValue();
                                    if (!quick)
                                        return;
                                    quick = quick.toLowerCase();
                                    console.log("Quickfind:" + quick);
                                    if (quick.startsWith('i') || quick.startsWith('z') || quick.startsWith('r'))
                                    {
                                        document.location.href = '#' + quick;
                                    }

                                }
                            }


                        ]
                    }
                ]

            }
        ],
        listeners: [
            {
                fn: 'onMynestedlistActiveItemChange',
                event: 'activeitemchange',
                delegate: '#mynestedlist'
            }
        ]
    },
    onMynestedlistActiveItemChange: function(container, value, oldValue, eOpts) {

        alert("selection changed: " + value.action);
        if (value.action == 1)
        {

            var main = this.getComponent("mycontainer1");
            main.add(new WINK.view.PatientTabPanel());
            mail.doLayout();

        }
    }

});