/*
 * File: app/view/MyPowerPicker.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.view.MyPowerPicker', {
    extend: 'Ext.picker.Picker',

    requires: [
        'Ext.Button',
        'Ext.picker.Slot'
    ],

    config: {
        height: 500,
        slots: [
            {
                xtype: 'pickerslot',
                name: 'Sign',
                title: 'Sign'
            },
            {
                xtype: 'pickerslot',
                name: 'Power',
                title: 'Power'
            },
            {
                xtype: 'pickerslot',
                name: 'PowerDecimal',
                title: 'PowerDecimal'
            }
        ]
    },

    /*


    */
    constructor: function(arguments) {

                this.config.slots[0].data=[];
                this.config.slots[1].data=[];
                this.config.slots[2].data=[];

                var i=0;
                this.config.slots[0].data[i]={text:"-",value:-1};
                i++;
                this.config.slots[0].data[i]={text:"+",value:+1};


                i=0;
                for(var v=0;v<20;v++,i++){
                    this.config.slots[1].data[i]={text:v,value:v};
                }


                i=0;
                for(var v=0;v<100;v=v+25, i++){
                   this.config.slots[2].data[i]={text:v,value:v/100};
                }


                this.callParent(arguments);
    }

});