/*
 * File: app/view/PatientTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.view.PatientTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.PatientTabPanel',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Toggle',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.field.Email',
        'Ext.carousel.Carousel'
    ],

    config: {
        activeItem: 1,
        centered: false,
        layout: {
            type: 'card',
            animation: 'fade'
        },
        items: [
            {
                xtype: 'container',
                title: 'Patient Details',
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'Patient',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'First Name'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Last Name'
                            },
                            {
                                xtype: 'togglefield',
                                label: 'Gender',
                                activeLabel: 'Male',
                                inactiveLabel: 'Female'
                            },
                            {
                                xtype: 'datepickerfield',
                                label: 'DOB',
                                placeHolder: 'mm/dd/yyyy'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        title: 'Contact ',
                        items: [
                            {
                                xtype: 'emailfield',
                                label: 'Email',
                                placeHolder: 'email@example.com'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Home'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Cell'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Work'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Fax'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        title: 'Address',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'Civic Number'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Unit'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Street Name'
                            },
                            {
                                xtype: 'textfield',
                                label: 'City'
                            },
                            {
                                xtype: 'selectfield',
                                label: 'Country'
                            },
                            {
                                xtype: 'selectfield',
                                label: 'Province/St'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Postal/Zip'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'carousel',
                title: 'Attachemnts'
            }
        ]
    }

});