/*
 * File: app/view/PowerSelectField.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.view.PowerSelectField', {
    extend: 'Ext.field.Select',
    alias: 'widget.powerselectfield',

    config: {
        labelWidth: '0%',
        usePicker: true
    },

    getPhonePicker: function() {
                if(!this.picker)
                {
                this.picker = new WINK.view.MyPowerPicker();
                }

                return this.picker;
    },

    getTabletPicker: function() {
        return this.getPhonePicker();
    },

    showPicker: function() {
            var me = this;
            //var store = me.getStore();
            //var value = me.getValue();

            if (me.getReadOnly()) {
                    return;
                }

                me.isFocused = true;


                    var picker = me.getPhonePicker();



        // name = me.getName(),
                    //  pickerValue = {};

                    // pickerValue[name] = value;
                    // picker.setValue(pickerValue);



                    if (!picker.getParent()) {
                        Ext.Viewport.add(picker);
                    }

                    picker.show();



    }

});