/*
 * File: app/view/QuickProductSelectionPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.view.QuickProductSelectionPanel', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Button',
        'Ext.Toolbar'
    ],

    config: {
        parentView: null,
        style: 'background: white',
        scrollable: 'vertical',
        invoicePanel: null,
        items: [
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton7',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton8',
                style: 'float: left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton9',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton10',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton11',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton12',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton13',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton14',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton15',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton16',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton17',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton18',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton19',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton20',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton21',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton22',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton23',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton24',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton25',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton26',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton27',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton28',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton29',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton30',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton31',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton32',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton33',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton34',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton35',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton36',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton37',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton38',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton39',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton40',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton41',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'button',
                cls: 'mainMenuButton',
                height: 125,
                itemId: 'mybutton42',
                style: 'float:left',
                width: 125,
                text: 'Quicksale'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'mybutton59',
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybutton59Tap',
                event: 'tap',
                delegate: '#mybutton59'
            }
        ]
    },

    onMybutton59Tap: function(button, e, eOpts) {


        this.getParentView().setActiveItem(this.getInvoicePanel());

    }

});