/*
 * File: app/view/RxWorksheetPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.view.RxWorksheetPanel', {
    extend: 'Ext.form.Panel',
    requires: [
        'WINK.view.PowerSelectField',
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.field.Slider',
        'Ext.SegmentedButton',
        'Ext.Button'
    ],
    loadRxWorksheet: function(rxWorksheetModel) {
           this.setRecord(rxWorksheetModel);
    },
    config: {
         border: '0 0 1 0',
        style: 'border-style:solid; border-color:darkgrey',
        items: [
            {
                xtype: 'container',
                layout: {
                    type: 'vbox',
                    align: 'start'
                },
                items: [
                    {
                        xtype: 'container',
                        layout: {
                            type: 'hbox',
                            align: 'start'
                        },
                        items: [
                            {
                                xtype: 'fieldset',
                                width: 150,
                                title: 'Far PD',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        label: 'R',
                                        labelWidth: '20%',
                                        name: 'r_farpd'
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: 'L',
                                        labelWidth: '20%',
                                        name: 'l_farpd'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                width: 150,
                                title: 'Near PD',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        label: 'R',
                                        labelWidth: '20%',
                                        name: 'r_closepd'
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: 'L',
                                        labelWidth: '20%',
                                        name: 'l_closepd'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                width: 150,
                                title: 'Height',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        label: 'R',
                                        labelWidth: '20%',
                                        name: 'r_height'
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: 'L',
                                        labelWidth: '20%',
                                        name: 'l_height'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: {
                            type: 'hbox',
                            align: 'start'
                        },
                        items: [
                            {
                                xtype: 'fieldset',
                               
                                width:500,
                                title: 'Frame',
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        label: 'Source',
                                        name: 'framesrc',
                                        options: [
                                            {text: 'Patient Own Frame', value: 0},
                                            {text: 'From Stock', value: 1},
                                            {text: 'To Order', value: 2}
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: {
                            type: 'hbox',
                            align: 'start'
                        },
                        items: [
                            {
                                xtype: 'fieldset',
                              
                                width:500,
                                items: [
                                    {
                                        xtype: 'textareafield',
                                        label: 'Lab Instructions',
                                        maxRows: 4,
                                        name: 'labinstructions'
                                    }
                                ]
                            }


                        ]
                    }

                ]
            }
        ]
    }

});