/*
 * File: app/view/RxWorksheetPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.view.RxWorksheetPanel', {
    extend: 'Ext.Panel',

    requires: [
        'WINK.view.PowerSelectField',
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.field.Slider',
        'Ext.SegmentedButton',
        'Ext.Button'
    ],

    config: {
        items: [
            {
                xtype: 'container',
                layout: {
                    type: 'hbox',
                    align: 'start'
                },
                items: [
                    {
                        xtype: 'fieldset',
                        width: 203,
                        title: 'SPH',
                        items: [
                            {
                                xtype: 'selectfield',
                                label: '',
                                labelWidth: '0%'
                            },
                            {
                                xtype: 'selectfield',
                                label: '',
                                labelWidth: '0%'
                            },
                            {
                                xtype: 'powerselectfield'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        title: 'MyFieldSet2',
                        items: [
                            {
                                xtype: 'sliderfield',
                                label: 'SPH',
                                value: [
                                    0
                                ],
                                increment: 0.25,
                                maxValue: 40,
                                minValue: -40
                            },
                            {
                                xtype: 'textfield',
                                label: 'Field'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Field'
                            }
                        ]
                    },
                    {
                        xtype: 'segmentedbutton',
                        items: [
                            {
                                xtype: 'button',
                                text: 'MyButton1'
                            },
                            {
                                xtype: 'button',
                                text: 'MyButton2'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});