require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

$RNFirebaseAsStaticFramework = true

target 'WinkTouch' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'WinkTouchTests' do
    inherit! :complete
    # Pods for testing
  end

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseABTesting', :modular_headers => true
  pod 'FirebaseCoreDiagnostics', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true
  pod 'FirebaseRemoteConfig', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'WinkTouch-tvOS' do
  # Pods for WinkTouch-tvOS

  target 'WinkTouch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
