/*
 * File: app/store/LocationStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.store.BarcodeResponseStore', {
    extend: 'Ext.data.Store',
    requires: [
        'WINK.model.BarcodeResponse'
    ],
    sortList: function() {
        this.sort([
            {
                property: 'isInventory',
                direction: 'ASC'

            },
            {
                property: 'storeInventory',
                direction: 'DESC'

            },
            {
                property: 'entrepriseInventory',
                direction: 'DESC'

            },
            {
                property: 'fkproduct_idproduct.name',
                direction: 'ASC'

            }
        ]);
        // this.group();

    },
    config: {
        data: [
        ],
        model: 'WINK.model.PatientHistoryTree',
        grouper: {
            groupFn: function(record) {


                if (!record.get('isInventory'))
                    return "Services and Non Inventory Products";
                if (record.get('storeInventory') > 0)
                    return "Found in Current Store";

                if (record.get('entrepriseInventory') > 0)
                    return "Found in Another Store";

                return "Not Found In Inventory";

            },
            sortProperty: 'type'
        },
        sorters: [
            {
                property: 'isInventory',
                direction: 'ASC'

            },
            {
                property: 'storeInventory',
                direction: 'DESC'

            },
            {
                property: 'entrepriseInventory',
                direction: 'DESC'

            },
            {
                property: 'fkproduct_idproduct.name',
                direction: 'ASC'

            }
        ]
    }
});