/*
 * File: app/store/LocationStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.store.CountrySubdivisionStore', {
    extend: 'Ext.data.Store',
    requires: [
        'WINK.model.CountrySubdivision'
    ],
    config: {
        model: 'WINK.model.CountrySubdivision',
        proxy: {
            type: 'rest',
            url: WINK.Utilities.getRestURL() + 'countries/subdivision/' + WINK.Utilities.getAccountId()

        },
        sorters: [
            {
                property: "name",
                direction: "ASC"
            }
        ]
    }
});