/*
 * File: app/store/LocationStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.store.PatientHistoryStore', {
    extend: 'Ext.data.Store',
    requires: [
        'WINK.model.Patient',
        'WINK.model.PatientHistoryTree'
    ],
    sortHistory: function() {
        this.sort([
            {
                property: 'type',
                direction: 'ASC'

            },
            {
                property: 'date',
                direction: 'DESC'

            }
        ]);
       // this.group();

    },
    config: {
        data: [
        ],
        model: 'WINK.model.PatientHistoryTree',
        grouper: {
            groupFn: function(record) {
                if (record.get('type') == 0)
                    return "Patient Details";

                if (record.get('type') == 1)
                    return "Exams";
                if (record.get('type') == 2)
                    return "Appointments";
                if (record.get('type') == 3)
                    return "Photobooth";

                if (record.get('type') == 4)
                    return "Open Jobs";
                if (record.get('type') == 5)
                    return "Closed Jobs";
                return record.get('type');

            },
            sortProperty: 'type'
        },
        sorters: [
            {
                property: 'type',
                direction: 'ASC'

            }]
    }
});