/*
 * File: app/store/LocationStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.store.PatientHistoryStore', {
    extend: 'Ext.data.Store',
    requires: [
        'WINK.model.Patient'
    ],
    config: {
        data: [
            {
                Type: 0,
                ID: 1,
                Label: 'Christian Mokbel',
                Icon: '',
                Date: ''
            },
            {
                Type: 4,
                ID: 1,
                Label: '2015-01-01 20.00',
                Icon: '',
                Date: ''
            },
            {
                Type: 4,
                ID: 1,
                Label: '2015-01-01 20.00',
                Icon: '',
                Date: ''
            },
            {
                Type: 5,
                ID: 1,
                Label: '2015-01-01 20.00',
                Icon: '',
                Date: ''
            },
            {
                Type: 5,
                ID: 1,
                Label: '2015-01-01 20.00',
                Icon: '',
                Date: ''
            }
        ],
        model: 'WINK.model.PatientHistory',
        storeId: 'PatientHistoryStore',
        grouper: {
            groupFn: function(record) {
                if (record.get('Type') == 0)
                    return "Patient Details";

                if (record.get('Type') == 1)
                    return "Exams";
                if (record.get('Type') == 2)
                    return "Appointments";
                if (record.get('Type') == 3)
                    return "Photobooth";

                if (record.get('Type') == 4)
                    return "Open Jobs";
                if (record.get('Type') == 5)
                    return "Closed Jobs";
                return record.get('Type');

            },
            sortProperty: 'Type'
        }
    }
});