/*
 * File: app/store/LocationStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.store.PatientStore', {
    extend: 'Ext.data.Store',

    requires: [
        'WINK.model.Patient'
    ],

    config: {
        data: [
            {
                ID: 1,
                FirstName: 'Christian',
                LastName: 'Mokbel'
            },
            {
                ID: 2,
                FirstName: 'Ted',
                LastName: 'Harrar'
            },
            {
                ID: 2,
                FirstName: 'Ted',
                LastName: 'Harrar'
            },
            {
                ID: 2,
                FirstName: 'Ted',
                LastName: 'Harrar'
            },
            {
                ID: 2,
                FirstName: 'Ted',
                LastName: 'Harrar'
            },
            {
                ID: 2,
                FirstName: 'Ted',
                LastName: 'Harrar'
            },
            {
                ID: 2,
                FirstName: 'Ted',
                LastName: 'Harrar'
            },
            {
                ID: 2,
                FirstName: 'Ted',
                LastName: 'Harrar'
            },
            {
                ID: 2,
                FirstName: 'Ted',
                LastName: 'Harrar'
            },
            {
                ID: 2,
                FirstName: 'Ted',
                LastName: 'Harrar'
            },
            {
                ID: 2,
                FirstName: 'Ted',
                LastName: 'Harrar'
            },
            {
                ID: 2,
                FirstName: 'Ted',
                LastName: 'Harrar'
            },
            {
                ID: 2,
                FirstName: 'Ted',
                LastName: 'Harrar'
            },
            {
                ID: 2,
                FirstName: 'Ted',
                LastName: 'Harrar'
            },
            {
                ID: 2,
                FirstName: 'Ted',
                LastName: 'Harrar'
            },
            {
                ID: 2,
                FirstName: 'Ted',
                LastName: 'Harrar'
            }
            
            
            
            
            
        ],
        model: 'WINK.model.Patient',
        storeId: 'PatientStore',
        grouper: {
            groupFn: function(record) {
                return record.get('LastName').substr(0, 1);
            },
            sortProperty: 'LastName'
        }
    }
});