/*
 * File: app/store/TaxCodeStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.store.PaymentMethodStore', {
    extend: 'Ext.data.Store',
    requires: [
        'WINK.model.PaymentMethod'
    ],
    config: {
        data: [],
        model: 'WINK.model.PaymentMethod',
        proxy: {
            type: 'rest',
            url: WINK.Utilities.getRestURL() + 'paymentmethods',
            withCredentials: true,
            useDefaultXhrHeader: false
        },
        sorters: [
            {
                property: "name",
                direction: "ASC"
            }
        ]

    }
});