/*
 * File: app/store/TaxCodeStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WINK.store.TaxCodeStore', {
    extend: 'Ext.data.Store',

    requires: [
        'WINK.model.TaxCode'
    ],

    config: {
        data: [
            {
                id: 690,
                code: 'Q'
            },
            {
                id: 804,
                code: 'E'
            }
        ],
        model: 'WINK.model.TaxCode',
        storeId: 'TaxCodeStore'
    }
});