name: Build & Deploy DEV

on:
  workflow_dispatch:
  push:
    branches:
      - main_BigBang

env:
  NODE_VERSION: '20.x'
  ENVIRONMENT: 'prod'

jobs:
  build-and-deploy:
    runs-on: [self-hosted]
    environment: 'prod'

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build, test
        run: |
          npm install --legacy-peer-deps
          npm run build:web:${{env.ENVIRONMENT}} --if-present
          npm test

      - name: Push artifact to Nexus
        run: |
          for f in ./dist/*; do    
            echo $f
            curl -v --user builder:${{ secrets.BUILDER_CREDENTIALS }} --upload-file $f  http://10.5.5.101/repository/internal/EMR/WinkTouch/bundle-${{ GITHUB.RUN_NUMBER }}/"${f##*/}"
          done

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload to the storage account
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload-batch --source ./dist --destination '$web' --account-name ${{ vars.STORAGE_ACCOUNT }}
      - name: logout
        run: |
          az logout
